[profile.default]
solc-version = "0.8.16"
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./deployed/"}]

[profile.production]
solc-version = "0.8.16"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mumbai = "https://matic-mumbai.chainstacklabs.com"
polygon = "${POLYGON_RPC_URL}"
aurora = "https://mainnet.aurora.dev"
aurora-testnet = "https://testnet.aurora.dev"
arbitrum-testnet = "https://sepolia-rollup.arbitrum.io/rpc"

