[profile.default]
solc-version = "0.8.16"
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./deployed/"}]

[profile.production]
solc-version = "0.8.16"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
aurora = "https://mainnet.aurora.dev"
aurora-testnet = "https://testnet.aurora.dev"
base-sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
polygon = "${POLYGON_RPC_URL}"
polygon-amoy = "https://rpc-amoy.polygon.technology/"
turbo = "https://rpc-0x4e45415f.aurora-cloud.dev"
