[profile.default]
solc-version = "0.8.16"
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200


[profile.production]
solc-version = "0.8.16"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mumbai = "https://matic-mumbai.chainstacklabs.com"
polygon = "https://polygon-rpc.com"

[etherscan]
mumbai = {key = "${POLYGONSCAN_MUMBAI_API_KEY}", url = "https://api-testnet.polygonscan.com/api/"}
